dist: trusty
sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
  - "./node_modules"
node_js:
- '8.11.1'
before_install:
- npm install -g vuepress
install:
- npm install
script:
- npm run ci
deploy:
  provider: firebase
  api_key:
    secure: 4pQ_eb6BLmkyPBlfCgL5Aw
  skip_cleanup: true
  app: travay
  on:
    repo: farahbrunache/travay-colony-vuejs-dapp
